version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: <TASK_DEFINITION> # Akan diisi otomatis oleh Pipeline
        LoadBalancerInfo:
          ContainerName: "apps-tf" #
          ContainerPort: 8080