name: CI/CD to ECS

on:
  push:
    branches: [ main, devsecops-task-definition ]

jobs:
  build:
    name: Build & Push to ECR
    runs-on: ubuntu-latest
    environment: prod
    # Mendefinisikan output agar bisa dibaca oleh job deploy
    outputs:
      image: ${{ steps.build_and_push.outputs.image }}
    env:
      ECR_REPOSITORY: apps-tf
      IMAGE_TAG: ${{ github.sha }} # Menggunakan SHA commit agar image selalu unik

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push image to Amazon ECR
      id: build_and_push
      run: |
        # Membentuk string URL Image
        IMAGE_URI=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
        
        # Proses Build dan Push
        docker build -t $IMAGE_URI .
        docker push $IMAGE_URI
        
        # Menyimpan nilai IMAGE_URI ke output GitHub Actions
        echo "image=$IMAGE_URI" >> $GITHUB_OUTPUT

  deploy:
    name: Deploy to ECS
    runs-on: ubuntu-latest
    environment: prod
    needs: build # Menunggu job build selesai
    env:
      ECS_SERVICE: app-service
      ECS_CLUSTER: app-gunawan-cluster

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Render Amazon ECS task definition
      id: render-task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: task-definition.json
        container-name: apps-tf
        # Mengambil data output dari job build secara langsung
        image: ${{ needs.build.outputs.image }}

    - name: Deploy to Amazon ECS service
      uses: aws-actions/amazon-ecs-deploy-task-definition@v2
      with:
        task-definition: ${{ steps.render-task-def.outputs.task-definition }}
        service: ${{ env.ECS_SERVICE }}
        cluster: ${{ env.ECS_CLUSTER }}
        wait-for-service-stability: true